# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Title (appears only in the PDF properties)
#+AUTHOR: Lucas Mello Schnorr

#+STARTUP: overview indent
#+LANGUAGE: pt-br
#+OPTIONS: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+OPTIONS: author:nil title:nil date:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_CLASS: IEEEtran
#+LATEX_CLASS_OPTIONS: [conference,letter,10pt,final]

# You need at least Org 9 and Emacs 24 to make this work.
# If you do, just type make (thanks Luka Stanisic for this).

* SBAC-PAD CFP                                                     :noexport:

Call for Papers

The 38th IEEE/SBC Symposium on Computer Architecture and High
Performance Computing will take place from October 14 to 16 at Madrid,
Spain.


SBAC-PAD is an annual international conference series, which presents
the latest trends, current research and developments, and novel tools
and applications in the fields of Computer Architecture,
High-Performance Computing, and Parallel and Distributed Computing
technologies. SBAC-PAD is open to industry, faculty, researchers,
practitioners, and undergraduate and graduate students from around the
world. Its scientific program is composed of high-quality submitted
papers, selected by a thorough peer review process, and invited talks
from renowned researchers.

Important dates

    Paper submission deadline: May 22nd, 2026 May 29th, 2026 (first
    extension) June 7th, 2026 (firm deadline) (AoE)
    
    Rebuttal period: July 22nd - 27th, 2026
    Author notification: August 3rd, 2026
    Camera-ready submission: September 5th, 2026

Tracks

Authors are invited to submit original manuscripts to one of six
tracks that address challenges in any of the following areas related
to the fields of Computer Architecture (CA) and High-performance and
Distributed Computing (HPDC).

    Track 1 - System Software: Focuses on the design, implementation,
    and optimization of operating systems, compilers, runtimes, and
    middleware for high-performance, parallel, and distributed
    computing environments. Topics include virtualization, scheduling,
    resource management, and programming support for emerging
    architectures.
    
    Track 2 - Computer Architecture: Covers advances in processor,
    memory, interconnect, and accelerator design, including GPUs,
    FPGAs, and near-data processing. This track also welcomes
    contributions on reconfigurable, energy-efficient, resilient, and
    secure architectures for modern computing systems.
    
    Track 3 - Distributed Systems, Networking and Storage: Explores
    scalable distributed infrastructures such as clouds, clusters, and
    edge/fog systems. It also includes work on networking
    technologies, data management, storage systems, and I/O frameworks
    for data-intensive and high-throughput workloads.
    
    Track 4 - Parallel Applications and Algorithms: Dedicated to the
    development and analysis of parallel and distributed algorithms,
    programming models, and real-world scientific and engineering
    applications. Submissions addressing performance, scalability, and
    resilience on modern architectures are particularly encouraged.
    
    Track 5 - Performance Evaluation: Focuses on benchmarking,
    modeling, simulation, and analytical methods for evaluating and
    predicting the performance of hardware and software
    systems. Topics include power-aware and predictive performance
    models, as well as tools for profiling and optimization.
    
    Track 6 - Parallel and Distributed Computing for AI and Data
    Analytics: Encompasses AI and machine learning methods applied to
    computer architecture and high-performance computing, as well as
    the use of HPC for AI workloads. It also includes tools,
    frameworks, and data-driven approaches that enhance productivity
    and insight in large-scale computing environments.   

The program committee will select the top-ranked papers as finalists,
and one paper will be selected during the conference as the Best
Paper.

Paper guidelines

Paper submissions must be in English, have 10 pages maximum (excluding
the references), and follow the IEEE conference manuscript formatting
guidelines for double-column text using a single-spaced 10-point font
on 8.5 × 11-inch pages. Templates are available from
http://www.ieee.org/conferences/publishing/templates.html. Papers that
do not meet these requirements might be rejected without a review. To
be published in the conference proceedings and to be eligible for
publication at the IEEE Xplore, one of the authors must register at
the full rate and present his/her work at the conference.

The SBAC-PAD 2026 submissions will undergo a double-anonymized review
process, where reviewers will not know the authors’ identities, and
vice-versa. Therefore, authors should “anonymize” their submission by
adopting the following guidelines, otherwise papers will be rejected
without review:

Authors cannot include their names, affiliations, funding sources, or
acknowledgments in any part of the for-review version of their paper;

Self-references that are relevant to the work are allowed, but they
should not appear in the text in the first person. Instead, they
should be referenced in the third person, like “Smith et al. found
that… [4].”, and;

For the authors’ own unpublished work use anonymous citations.
Paper submission

Submission must be done using EasyChair: 

* *The Paper*                                                          :ignore:
** Latex configurations                                             :ignore:
** Frontpage                                                        :ignore:
#+BEGIN_EXPORT latex
\title{MPI-Based 3D Anisotropic RTM with Fletcher's Method and Ghost Cell Halo Exchange}
\author{\IEEEauthorblockN{Vinícius Daniel Spadotto, Lucas Mello Schnorr}
\IEEEauthorblockA{Institute of Informatics, Porto Alegre, Brazil}}
#+END_EXPORT

#+LaTeX: \maketitle

** Abstract                                                         :ignore:

#+LaTeX: \begin{abstract}

Put the abstract here.

#+LaTeX: \end{abstract}

** Introduction
** Methods and Materials
:PROPERTIES:
:CUSTOM_ID: sec.methods
:END:

** Results
:PROPERTIES:
:CUSTOM_ID: sec.results
:END:

** Conclusion
:PROPERTIES:
:CUSTOM_ID: sec.conclusion
:END:

** Acknowledgments                                                  :ignore:

#+LATEX:\section*{Acknowledgements}

All experiments in this work used the PCAD platform,
http://pcad.inf.ufrgs.br, at INF/UFRGS. This work was partially
supported by Petrobras through an agreement with UFRGS under 2.20.2205
(361), SAP 23078.450001/2022-17, and SIC 2020/00182-5.

** References                                                       :ignore:

# See next section to understand how refs.bib file is created.

#+LATEX: \bibliographystyle{IEEEtran}
#+LATEX: \bibliography{refs}

* Bib file is here                                                 :noexport:

Tangle this file with C-c C-v t

#+begin_src bib :tangle refs.bib
@article{orgmode,
  author =	"Eric Schulte and Dan Davison and Thomas Dye and Carsten Dominik",
  title =	"A Multi-Language Computing Environment for Literate Programming and Reproducible Research",
  journal =	"J. of Stat. Soft.",
  volume =	"46",
  number =	"3",
  day =  	"25",
  year = 	"2012",
  CODEN =	"JSSOBK",
  ISSN = 	"1548-7660",
  bibdate =	"2011-10-03",
  accepted =	"2011-10-03",
  acknowledgement = "",
  submitted =	"2010-12-22",
}

@incollection{schnorr2013visualizing,
  title={Visualizing More Performance Data Than What Fits on Your Screen},
  author={Schnorr, Lucas M and Legrand, Arnaud},
  booktitle={Tools for High Performance Computing 2012},
  pages={149--162},
  year={2013},
  publisher={Springer}
}


#+end_src
* Emacs setup                                                      :noexport:

# Local Variables:
# eval: (add-to-list 'load-path ".")
# eval: (require 'ox-extra)
# eval: (ox-extras-activate '(ignore-headlines))
# eval: (add-to-list 'org-latex-classes '("IEEEtran" "\\documentclass{IEEEtran}" ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}") ("\\subsubsection{%s}" . "\\subsubsection*{%s}") ("\\paragraph{%s}" . "\\paragraph*{%s}") ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# End:
